[project]
name = "prac3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=24.10.0",
    "click>=8.1.8",
    "matplotlib>=3.10.0",
    "networkx>=3.4.2",
    "pathlib>=1.0.1",
]
