[project]
name = "prac4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.7",
    "ollama>=0.4.4",
    "uvicorn>=0.32.1",
]
